services:
  mysql:
    restart: always
    image: mysql:9.2
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    command: --init-file /data/init.sql
    volumes:
      - ./init.sql:/data/init.sql
