name: build
on:
  workflow_call:
    secrets:
      gh-token:
        required: true
      dh-username:
        required: true
      dh-token:
        required: true
    inputs:
      repository:
        required: true
        type: string
        description: Docker hub repository's name
      context:
        type: string
        description: relative folder to find Dockerfile
        default: .
    outputs:
      branch-name:
        value: ${{ jobs.docker-push.outputs.branch-name }}
        description: name of the branch
      git-sha:
        value: ${{ jobs.docker-push.outputs.git-sha }}
        description: short SHA of the commit

jobs:
  docker-push:
    runs-on: ubuntu-latest
    outputs:
      git-sha: ${{ steps.git-context.outputs.git-sha }}
      branch-name: ${{ steps.git-context.outputs.branch-name }}
    steps:
      - name: Retrieve git context metadata
        shell: bash
        id: git-context
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ $GITHUB_REF = *refs/heads/* ]]; then
            echo "branch-name=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
            echo "git-sha=`echo $GITHUB_SHA | cut -c1-7`" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            export RESPONSE=`curl -s --request GET --url "${{ github.event.issue.pull_request.url }}" --header "Authorization: Bearer ${{ env.GH_TOKEN }}"`
            echo "branch-name=`echo $RESPONSE | jq -r .head.ref`" >> $GITHUB_OUTPUT
            echo "git-sha=`echo $RESPONSE | jq -r .head.sha | cut -c1-7`" >> $GITHUB_OUTPUT
          else
            echo "branch-name=$GITHUB_HEAD_REF" >> $GITHUB_OUTPUT
            echo "git-sha=`echo ${{ github.event.pull_request.head.sha }} | cut -c1-7`" >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.git-context.outputs.branch-name }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dh-username }}
          password: ${{ secrets.dh-token }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.context}}/Dockerfile
          push: true
          tags: |
            ${{ inputs.repository }}:${{ steps.git-context.outputs.git-sha }}
            ${{ inputs.repository }}:${{ steps.git-context.outputs.branch-name }}
          build-args: |
            GH_ACCESS_TOKEN=${{ secrets.gh-token }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.gh-token }}
        env:
          DOCKER_BUILDKIT: 1